name: vns 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET Web API
      run: dotnet publish vns-be/ -c Release -o ./publish

    - name: Copy Files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: root
        password: ${{ secrets.EC2_PASSWORD }}
        source: "publish/*"
        target: "/home/ubuntu/vns-api"
        strip_components: 1

    - name: Restart API on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: root
        password: ${{ secrets.EC2_PASSWORD }}
        script: |
          sudo systemctl restart vns-api
